### ISSUE TITLE
prevent symbol overriding by another type

### ISSUE THREAD

**Issue by antis81** [sasq64/badass#19]
After the merge of #18 I noticed that doesn't handle a (rather important) corner case…

The following test shows this is not handled by the parser yet:

```asm
symbol_0  ; label
;!error <TBD>
symbol_0  = "overrides symbol_0 (changing type from label to var)"
```

On the other hand re-assigning a var is fine:

```asm
symbol_1 = 1233
symbol_1 = symbol_1 + 1  ; re-assigning is good :)
```

This can be handled with the "final" flag and basically relies on the "const" definition of a label type.

Note this only applies to assignment types as other symbols (macro, enum, section, … ) are named "anonymously" - thus clearly distinguish from each other.

**Comment by sasq64** [comment]
Testing now, and the second case actually fails.

The first case gives a data type error, which I think is OK, you shouldn't change types of
variables.

Opening #37 instead.
