### ISSUE TITLE
Can newline be optional at EOT?

### ISSUE THREAD

**Issue by antis81** [sasq64/badass#24]
Currently bass errors out if no newline is given before EOF:

```asm
; no newline before EOF -> error
```

vs

```asm
; newline(s) before EOF -> ok


```

**Comment by sasq64** [comment]
It's a quirk of the grammar that I found hard to get around. But bass always adds an extra LF before parsing for this reason I think ?

**Comment by antis81** [comment]
>But bass always adds an extra LF before parsing for this reason I think ?

Actually it doesn't add an LF before EOF (btw. I am on Linux -> thus talking LF here).

EDIT (answered by self :slightly_smiling_face:): ~~Btw. is it PEG's grammar format we are talking?~~

**Comment by antis81** [comment]
Found it -> The "EOL" rule can prbly be extended to simply include (reference?) `EOT -> !.` (if no character follows we have both EOL and EOT!)

**Comment by antis81** [comment]
Ahaha… the issue tricked me! :see_no_evil: Wondered why this isn't reproducible with "usual" asm files - it only happens with `!include / !script`. Since "followup text" is simply added to the same line this messes up the whole string.

Example:

```asm
; no_newline.asm
; just some dummy code (without newline!)
  lda #42
```

```asm
; main file
!org 0x1234

!include "no_newline.asm"  ; make sure code follows directly on the next line (skips an "accidental" newline)
start_of_test: ; -> syntax error -> parser reads the now invalid label line "  lda #42start_of_test:"
```

As in my above comment making EOT also an EOL should fix it. Will add a test as well so this is always checked.

**Comment by antis81** [comment]
Mmm… nope! The issue must be related to my project structure and somehow triggers a corner case (usually it works). Also the above test works fine with and w/o LF at the end. Difficult…

**Comment by antis81** [comment]
Closing -> new issue
