### ISSUE TITLE
[request] symbol attributes

### ISSUE THREAD

**Issue by antis81** [sasq64/badass#27]
In some cases it can be helpful to define macro parameters read-only (const) and error out when trying a write operation. Here's a draft of what it could look like:

```asm
!macro m(foo:const, bar) {
  inc bar  ; ok: bar is not marked read-only
  
  ; a write "foo" would error out
  inc bar  ; error: bar is readonly
}
```

Also "assignments" could benefit from that:

```asm
value:const = 42

; same for local variables
label_0:
.value:const = 42
```

**Comment by sasq64** [comment]
I _think_ what you really want is for labels to always be constant across one pass.
So you should not be allowed to reassign labels. I think this is safer and has no big downside...

**Comment by antis81** [comment]
Mmh… yeah, even more this is checked with the "final" flag now (some corner cases remain).
