### ISSUE TITLE
bug: macro tries to redefine local label

### ISSUE THREAD

**Issue by antis81** [sasq64/badass#34]
Having the following situation:

```asm
!macro some_macro(v0) { 
.macro_label:
  ; some content 
  rts
}
```

It seems to work fine when the macro is instantiated within the same label context (same pass?):
```asm
label_0:
  some_macro(1)
  some_macro(2)
```

Fails when the macro is instantiated in *different* label contexts:
```asm
label_0: some_macro(1)
label_1: some_macro(2)  ;<--- fails with "already defined label __macro_<id>.macro_label"
```

Macro ID's should always be "unique" right?

And yes, I am totally aware that implementation of the "final" flag on symbols is incomplete. :innocent:

**Comment by sasq64** [comment]
Tested this now, seems to work.
