### ISSUE TITLE
unexpected behaviour for "!include"

### ISSUE THREAD

**Issue by antis81** [sasq64/badass#4]
Hey,
just porting a bigger project from kick assembler and it raised some questions on the include mechanism:

Docs state that files are always included relatively to the "current" file's path. The behavior seems to be different though and path is always relative to the "root" input file given in `bass -i <file.asm>` option.
    - Is there an option to edit the include search path maybe so i could work around that?

~~The `!include` directive currently includes files multiple times.~~ -> moved to #8 

Cheers, Nils

**Comment by sasq64** [comment]
This seems to be fixed
